// Concept and Structure in C++
// Types of function
// 1. Built - in function ,    2. User define function


// parts of function
// 1. function Declaration
// 2. function Definition
// 3. function Call

#include<iostream>
using namespace std;

//  Structure of function
int function_cpp (int x , float y) // 1.function Declaration
{
    // 2. function Definition
}

int main()
{
    // 3. function Call

}
