// Write a Program for if - Statement
#include<iostream>
using namespace std;

int main()
{
    int x ;
    cout<<"Enter the value for x :";
    cin>>x;

    if ( x > 0)
    {
        cout<<"The value of x greater than Zero"<<endl;
    }

    if ( x < 0)
    {
        cout<<"The value of x less than Zero"<<endl;
    }

    if( x == 0)
    {
        cout<<"The value of x is equal to Zero"<<endl;
    }



}